import type { LevelDefinition } from "@/types/assessment";

export const levels: LevelDefinition[] = [
  {
    level: 0,
    name: "Manual Labor",
    shortDescription: "Humans retain complete control. AI may assist with search or explanation, but the human remains the sole author.",
    humanRole: "Sole author and final decision-maker.",
    aiRole: "Search, explanation, autocomplete, or occasional suggestion.",
    typicalBehavior: ["Writes most or all code manually", "Reviews every character before it hits disk", "Uses AI similarly to documentation or search"],
    goodFor: ["Learning fundamentals", "High-stakes changes", "Deep debugging"],
    risks: ["Slow iteration", "Human bottlenecks", "Underuse of automation"],
    exampleWork: ["Ask AI to explain an API", "Search for examples", "Manually write and approve every change"],
    color: "gray",
  },
  {
    level: 1,
    name: "Assisted Tasks",
    shortDescription: "Developers delegate specific, discrete jobs to AI while handling critical work themselves.",
    humanRole: "Primary developer.",
    aiRole: "Task assistant for small, bounded jobs.",
    typicalBehavior: ["Delegates tests, comments, docstrings, and helpers", "Keeps critical logic human-led", "Reviews output before accepting it"],
    goodFor: ["Unit tests", "Documentation", "Boilerplate", "Small refactors"],
    risks: ["Mistaking small-task productivity for system capability", "Accepting low-quality minor changes"],
    exampleWork: ["Write a unit test", "Add a docstring", "Convert a function to TypeScript"],
    color: "blue",
  },
  {
    level: 2,
    name: "Active Partnership",
    shortDescription: "The developer pairs with AI like a colleague, often in a productive flow state inside coding tools.",
    humanRole: "Pair programmer, reviewer, and technical lead for the immediate task.",
    aiRole: "Junior colleague that can implement, refactor, debug, and suggest next steps.",
    typicalBehavior: ["Works continuously with AI in the editor", "Delegates routine implementation", "Alternates between AI generation and human review"],
    goodFor: ["Feature implementation", "Multi-step debugging", "Refactoring", "Test creation"],
    risks: ["Overtrusting the flow state", "Letting AI shape architecture accidentally", "Confusing velocity with quality"],
    exampleWork: ["Implement a bounded feature with supervision", "Patch a bug and add a regression test", "Use AI as a daily pair programmer"],
    color: "green",
  },
  {
    level: 3,
    name: "Human Oversight",
    shortDescription: "AI becomes the primary developer while humans shift toward management, review, and quality gates.",
    humanRole: "Manager, reviewer, planner, and quality gate.",
    aiRole: "Primary implementer across scoped tasks.",
    typicalBehavior: ["Runs agents on scoped tickets", "Reviews diffs and test results", "Spends more time supervising than typing code"],
    goodFor: ["Parallelized implementation", "Bug investigation", "Multi-file changes", "Backlog execution"],
    risks: ["Review fatigue", "Hidden regressions", "Large difficult-to-review diffs", "Poor task specification"],
    exampleWork: ["Assign agents to separate tickets", "Review agent PRs", "Let an agent investigate and patch a failing flow"],
    color: "amber",
  },
  {
    level: 4,
    name: "Autonomous with Guidance",
    shortDescription: "Humans write specs and workflows while agents execute for extended periods within guardrails.",
    humanRole: "Spec writer, planner, workflow designer, and evaluator.",
    aiRole: "Semi-autonomous executor that plans, implements, tests, and iterates within constraints.",
    typicalBehavior: ["Writes detailed specs", "Creates reusable skills or workflows", "Checks results after long-running agent work"],
    goodFor: ["Large migrations", "Repetitive feature families", "Product prototypes", "Internal tooling"],
    risks: ["Vague specs", "Tests becoming the only correctness definition", "Automation outrunning understanding"],
    exampleWork: ["Draft a feature spec and let an agent work for hours", "Build reusable skills", "Ask an agent to migrate a module and report passing tests"],
    color: "purple",
  },
  {
    level: 5,
    name: "Dark Factory",
    shortDescription: "A mostly autonomous system turns specs into software with little or no routine human involvement.",
    humanRole: "Optional upstream intent setter, owner, or governor.",
    aiRole: "Autonomous software production system.",
    typicalBehavior: ["Software is generated, tested, improved, and possibly deployed automatically", "System handles planning, coding, validation, and iteration internally"],
    goodFor: ["Constrained domains with strong evals", "Automated internal software generation", "Mature AI-native engineering systems"],
    risks: ["Loss of visibility", "Accountability gaps", "Misaligned output at scale", "Security and compliance failures"],
    exampleWork: ["Turn approved specs into deployed software", "Autonomous codebase maintenance", "Continuous product experiment generation"],
    color: "black",
  },
];

export function getLevel(level: number) {
  return levels.find((item) => item.level === level) ?? levels[0];
}
